import type { Metadata } from "next";
import { Container } from '@mui/material';

import './global.css';
import styles from './RootLayout.module.scss';

export const metadata: Metadata = {
  title: "Fast Tasks",
  description: "Generated by me",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <Container className={styles["root-container"]}>
          {children}
        </Container>
      </body>
    </html>
  );
}

export default RootLayout;
